### PR TITLE
the score/kill loops assumed 10 players; fixed

### PR DESCRIPTION
**Pull request by grahams**
Graphs would bork out if there are stats for fewer than 10 players.

Resubmitting to isolate the fix from other changes I made.

### CODE REVIEW

**Comment by niekcandaele** [comment]
Thanks again :smile: I've found the CI error, would you mind rebasing this PR once I finish?

**Comment by grahams** [comment]
sure thing

**Comment by niekcandaele** [comment]
https://github.com/niekcandaele/CSGO-RankMe-stats/pull/21

merged :) If you rebase, CI should pass properly

**Comment by niekcandaele** [comment]
I think something went wrong with that merge? There's no Github CI files

**Comment by grahams** [comment]
yeah, i'll fix it in the morning

**Comment by grahams** [comment]
Should be good, I definitely see the ci commits in the log.  Not sure what I screwed up yesterday.

**Comment by grahams** [comment]
Hrm.  I just got an email that it failed again.

**Comment by niekcandaele** [comment]
Ah yeah very weird, I see the CI running in your repo now. Failing because you don't have some secrets in your repo. I'll merge this because I really doubt your change had anything to do with CI failing :smile:

**Comment by grahams** [comment]
Haha ok, thanks...  I was about to create a new branch that started out rebased on to upstream/master, then re-cherry-pick my fix but I guess I won't bother now :)

**Comment by niekcandaele** [comment]
CI passed on master, so all good! Thanks for your contribution :) Did you say you had some other stuff to push aswell? If thats the case, I'll hold off on releasing a new version for now

**Comment by grahams** [comment]
The other change was adding an "Accuracy" column to the overview table.  If that's something you're interested in I can PR that too.  

I also noticed that ~all of the images in `static/img/weapons/` are duped (same names but mixed upper/lowercase versions).  I hadn't dug into figuring out which case is 'correct' yet, but on my Mac (with a case-insensitive fs) git had to pick one to check out..  I'll file a bug to track that for now.

**Comment by niekcandaele** [comment]
Sounds good!

**Pull request merged**
